kind: List 
apiVersion: v1 
items:  		
- apiVersion: v1 
  kind: Service 
  metadata: 
    name: kubia 
  spec: 
    clusterIP: None
    selector: 
      app: kubia 
    ports: 
    - name: http 
      port: 80
- apiVersion: apps/v1beta1 
  kind: StatefulSet 
  metadata: 
    name: kubia 
  spec: 
    serviceName: kubia 
    replicas: 2 
    template: 
      metadata: 
        labels: 
          app: kubia 
      spec: 
        containers: 
        - name: kubia 
          image: luksa/kubia-pet 
          ports: 
          - name: http 
            containerPort: 8080 
          
    